"""
Markdown report generator.

Writes a dated, human-readable .md report to outputs/reports/.
These reports are gitignored to prevent real analysis data from appearing in the public repo.
A sample output is included in data/examples/sample_report.md for portfolio display.
"""
from datetime import datetime
from pathlib import Path


def generate_markdown_report(
    insights: dict, aggregated: dict, config: dict
) -> str:
    """
    Write a PM-ready markdown report and return the file path.

    Args:
        insights: Output from insight_generator.generate_insights()
        aggregated: Output from orchestrator.aggregate_results()
        config: Brand config dict

    Returns:
        String path to the written report file
    """
    brand = config["brand"]["name"]
    output_dir = Path(config["reporting"]["output_dir"])
    output_dir.mkdir(parents=True, exist_ok=True)

    period = aggregated.get("period", datetime.now().strftime("%Y-W%V"))
    run_date = aggregated.get("run_date", datetime.now().strftime("%Y-%m-%d"))
    filename = f"{brand.lower()}_{period}.md"
    report_path = output_dir / filename

    report_path.write_text(_build_report(insights, aggregated, brand, period, run_date))
    return str(report_path)


def _build_report(
    insights: dict, aggregated: dict, brand: str, period: str, run_date: str
) -> str:
    lines = [
        f"# {brand} Customer Feedback Insights — {period}",
        f"",
        f"*Generated: {run_date} | Reviews analysed: {aggregated['review_count']} | Source: TrustPilot*",
        f"",
        f"---",
        f"",
        f"## Executive Summary",
        f"",
        insights.get("executive_summary", "_No summary generated._"),
        f"",
        f"**Sentiment trend:** {_trend_emoji(insights.get('sentiment_trend', 'stable'))} {insights.get('sentiment_trend', 'stable').capitalize()}",
        f"",
        f"---",
        f"",
        f"## Sentiment Breakdown",
        f"",
    ]

    dist = aggregated.get("sentiment_distribution", {})
    for sentiment in ["positive", "neutral", "negative"]:
        data = dist.get(sentiment, {"count": 0, "pct": 0})
        emoji = {"positive": "✅", "neutral": "➖", "negative": "❌"}[sentiment]
        bar = _progress_bar(data["pct"])
        lines.append(
            f"- {emoji} **{sentiment.capitalize()}**: {data['count']} reviews ({data['pct']}%) {bar}"
        )

    lines += [
        f"",
        f"---",
        f"",
        f"## Theme Distribution",
        f"",
        f"| Theme | Reviews |",
        f"|-------|---------|",
    ]

    for theme, count in aggregated.get("theme_frequency", {}).items():
        lines.append(f"| {theme.replace('_', ' ').title()} | {count} |")

    lines += [
        f"",
        f"---",
        f"",
        f"## Top Opportunities",
        f"",
    ]

    for i, opp in enumerate(insights.get("top_opportunities", []), 1):
        effort = opp.get("effort_estimate", "?")
        impact = opp.get("impact_estimate", "?")
        lines += [
            f"### {i}. {opp.get('opportunity', 'N/A')}",
            f"",
            f"**Evidence:** {opp.get('supporting_evidence', 'N/A')}",
            f"",
            f"**Suggested action:** {opp.get('suggested_action', 'N/A')}",
            f"",
            f"**Effort:** {_effort_badge(effort)} | **Impact:** {_impact_badge(impact)}",
            f"",
        ]

    lines += [
        f"---",
        f"",
        f"## Risks to Address",
        f"",
    ]

    for risk in insights.get("top_risks", []):
        urgency = risk.get("urgency", "monitor")
        lines += [
            f"- {_urgency_badge(urgency)} **{risk.get('risk', 'N/A')}** "
            f"({risk.get('frequency', '?')} reviews)",
        ]

    lines += [
        f"",
        f"---",
        f"",
        f"## Recommended Experiments",
        f"",
    ]

    for exp in insights.get("recommended_experiments", []):
        lines.append(f"- [ ] {exp}")

    lines += [
        f"",
        f"---",
        f"",
        f"*Report generated by [ecom-feedback-intelligence](https://github.com/jackhendonpapier/ecom-feedback-intelligence). "
        f"All data in this example is synthetic.*",
    ]

    return "\n".join(lines)


def _trend_emoji(trend: str) -> str:
    return {"improving": "📈", "stable": "➡️", "declining": "📉"}.get(trend, "➡️")


def _progress_bar(pct: float, width: int = 20) -> str:
    filled = round(pct / 100 * width)
    return f"`{'█' * filled}{'░' * (width - filled)}`"


def _effort_badge(effort: str) -> str:
    return {"low": "🟢 Low", "medium": "🟡 Medium", "high": "🔴 High"}.get(effort, effort)


def _impact_badge(impact: str) -> str:
    return {"low": "🟢 Low", "medium": "🟡 Medium", "high": "🔴 High"}.get(impact, impact)


def _urgency_badge(urgency: str) -> str:
    return {
        "monitor": "🔵 Monitor",
        "address_soon": "🟡 Address soon",
        "urgent": "🔴 Urgent",
    }.get(urgency, urgency)
